# Save this content as config.yaml
properties:
  configurationVersion: 0.2.0
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: installNotepadPlusPlus
      directives:
        description: "Install Notepad++"
      settings:
        id: Notepad++.Notepad++
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: installVLCPlayer
      directives:
        description: "Install VLC Media Player"
      settings:
        id: VideoLAN.VLC
        source: winget